export const mockup = {
    "steamID64": "7656112313123xxx",
    "privacy": "public",
    "steamID": "EXample",
    "onlineState": "in-game",
    "stateMessage": "In-Game<br/>Counter-Strike: Global Offensive",
    "avatarFull": "https://avatars.akamai.steamstatic.com/5fb4c2e486c41af058c70b13bd0101b629970670_full.jpg",
    "vacBanned": "0",
    "tradeBanState": "None",
    "isLimitedAccount": "0",
    "public": {
        "memberSince": "January 29, 2019",
        "realname": "Ramon 🍀 Namburg, Iermany",
        "summary": "<img src=\"https://community.akamai.steamstatic.com/economy/emoticon/radium\" alt=\":radium:\" class=\"emoticon\">󠁦󠁦󠁦󠁦󠁦󠁦󠁦The only culture i have is bacteria.󠁦󠁦󠁦󠁦󠁦󠁦󠁦<img src=\"https://community.akamai.steamstatic.com/economy/emoticon/radium\" alt=\":radium:\" class=\"emoticon\"><br><img src=\"https://community.akamai.steamstatic.com/economy/emoticon/SpellPlasma\" alt=\":SpellPlasma:\" class=\"emoticon\">Founder of the  <a class=\"bb_link\" href=\"https://steamcommunity.com/groups/greenisthebestcolour\" target=\"_blank\" rel=\"\" > Green Collectors Master Race</a> <img src=\"https://community.akamai.steamstatic.com/economy/emoticon/SpellPlasma\" alt=\":SpellPlasma:\" class=\"emoticon\"><br><img src=\"https://community.akamai.steamstatic.com/economy/emoticon/blanky2\" alt=\":blanky2:\" class=\"emoticon\">󠁦󠁦󠁦󠁦󠁦󠁦󠁦my favourite colour is Pink󠁦󠁦󠁦󠁦󠁦󠁦󠁦<img src=\"https://community.akamai.steamstatic.com/economy/emoticon/blanky2\" alt=\":blanky2:\" class=\"emoticon\"><br><img src=\"https://community.akamai.steamstatic.com/economy/emoticon/eatyourbroccoli\" alt=\":eatyourbroccoli:\" class=\"emoticon\">󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦 <a class=\"bb_link\" href=\"https://www.youtube.com/channel/UC-M-gP5tqNjeMGWdlmZWYAQ\" target=\"_blank\" rel=\"\" > YouTube </a> <img src=\"https://community.akamai.steamstatic.com/economy/emoticon/eatyourbroccoli\" alt=\":eatyourbroccoli:\" class=\"emoticon\">󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦󠁦<br><img src=\"https://community.akamai.steamstatic.com/economy/emoticon/greenparrot\" alt=\":greenparrot:\" class=\"emoticon\"> <a class=\"bb_link\" href=\"https://twitter.com/3razon_cs\" target=\"_blank\" rel=\"\" > Twitter </a> <img src=\"https://community.akamai.steamstatic.com/economy/emoticon/greenparrot\" alt=\":greenparrot:\" class=\"emoticon\"><br><img src=\"https://community.akamai.steamstatic.com/economy/emoticon/weed\" alt=\":weed:\" class=\"emoticon\"> <a class=\"bb_link\" href=\"https://steamcommunity.com/id/fourtwentysixtynine42069\" target=\"_blank\" rel=\"\" > Meme Floats </a> <img src=\"https://community.akamai.steamstatic.com/economy/emoticon/weed\" alt=\":weed:\" class=\"emoticon\"><br><br>",
        "gameName": "Counter-Strike: Global Offensive",
        "gameLink": "https://steamcommunity.com/app/730",
        //"gameIcon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/69f7ebe2735c366c65c0b33dae00e12dc40edbe4.jpg",
        "gameLogo": "https://cdn.akamai.steamstatic.com/steam/apps/730/capsule_184x69.jpg?t=1683566799",
        "mostGameName": "Counter-Strike: Global Offensive",
        "mostGameLink": "https://steamcommunity.com/app/730",
        //"mostGameIcon": "https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/69f7ebe2735c366c65c0b33dae00e12dc40edbe4.jpg",
        "mostGameLogo": "https://cdn.akamai.steamstatic.com/steam/apps/730/capsule_184x69.jpg?t=1683566799",
        "mostHoursPlayed": "16.0",
        "mostHoursOnRecord": "4,166",
        //"mostStatsName": "CSGO",
        //"groupID64": "103582791471109528",
        "groupName": "Green Collectors Master Race",
        "groupURL": "greenisthebestcolour",
        //"headline": "",
        "groupSummary": "Hey! <br><br>This is a place for people with full <b>green</b> Loadouts!<br>Or people who are working on one. <br>If you believe that green is superior to every other colour (yes, even pink), this group is for you! <br><br><div class=\"bb_h1\"> !HOW TO BECOME A MEMBER! </div><br>1. You have to have green CSGO skins! (sry, but this is a skins group)<br>2. You dont have to have super expensive skins, this group is for every budget!<br>3. BUT you have to be commited to green, which means:<br>-you need to have a green Loadout for eighter ct or t side (or both lol)<br>-you need to have a green skin for the most important guns (AK, AWP, etc.)<br>-Have some Kind of a green themed profile<br>-don‘t put your inventory on private<br>4. Request to become a member to join the group &lt;3 <br>(smol tipp: get some green skins first and THEN send request)<br><br>If you have any questions add me (3RaZoN) or join the Discord and ask there<br><br>[trying to scam/shark other group members will result in a perma ban from the group!]<br><br>Join the new and improved <a class=\"bb_link\" href=\"https://steamcommunity.com/linkfilter/?url=https://discord.gg/yZzkEbZ2cp\" target=\"_blank\" rel=\" noopener\" > Discord </a><span class=\"bb_link_host\">[discord.gg]</span> to get the whole green collectors community experience! <br><br><u> Join if you want: </u><br><ul class=\"bb_ul\"><li> Tips &amp; Tricks to improve your Profile<br></li><li> to showcase your profile<br></li><li> share your thoughts on  <br><br>also: Valve, pls add better green M4's, thx.<br><br><br>since 12/2021</li></ul>",
        "avatarFull": "https://avatars.akamai.steamstatic.com/3f43786f01135579128ec62b2974e1abc6d9317f_full.jpg",
        "memberCount": "384",
        "membersInChat": "65",
        "membersInGame": "60",
        "membersOnline": "170"
    }
}